changelog:
  exclude:
    labels:
      - chore
      - test
      - refactor
      - style
      - wip

  categories:
    - title: "✨ New and Better Features"
      labels:
        - feat
        - feature
        - enhancement
    - title: "🐛 Bug Fixes"
      labels:
        - fix
        - bugfix
        - bug
    - title: "🚨 Breaking Changes (Attention!)"
      labels:
        - breaking-change
      
    - title: "📚 Documentation and Code Tasks"
      labels:
        - docs
        - chore
        - refactor
        
